### ISSUE TITLE
Radarr, & Prowlarr Theme Issues

### ISSUE THREAD

**Issue by LlamaDuckGoose** [ThemeParkTycoon/theme.park#512]
**Describe the bug**
Looks like a similar issue has happened with the where the sidebar and search/top bar aren't getting themed correctly and say the default grey. I've tried a few different themes and they all have the same issue

**Theme Install Method** (Don't skip)
https://plugins.traefik.io/plugins/62947288ffc0cd18356a97c1/theme-park
Using these theme with treafik to rewrite the headers.
```
    radarr-themepark:
      plugin:
        traefik-themepark:
          app: radarr
          theme: hotline
    prowlarr-themepark:
      plugin:
        traefik-themepark:
          app: prowlarr
          theme: hotline
 ```

**Application Info** (Don't skip)
Radarr: 4.7.5.7809 (linuxserver) - Lastest
With this in the header:
<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/radarr/hotline.css">

Prowlarr: 1.7.4.3769 (linuxserver) - Lastest
With this in the header:
<link rel="stylesheet" type="text/css" href="https://theme-park.dev/css/base/prowlarr/hotline.css">

**To Reproduce**
Load Web Browser

**Expected behavior**
Theme should update the side and top bar like it does in the examples.

**Screenshots**
Sonarr (working)
![image](https://github.com/ThemeParkTycoon/theme.park/assets/55490546/e721d814-0673-4f2f-a48d-8b71505afbe7)

Radarr:
![image](https://github.com/ThemeParkTycoon/theme.park/assets/55490546/6837a079-7499-4655-95e6-c8acc5583a8d)
![image](https://github.com/ThemeParkTycoon/theme.park/assets/55490546/7d2cbae7-09d9-45c0-a63b-74ca72100572)
